services:
  - type: web
    name: PracticeSoft-BACKEND
    env: node
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm start
    preDeployCommand: npx prisma migrate deploy
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
